# Generated by Django 5.2.7 on 2025-10-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
