# Generated by Django 5.2.7 on 2025-10-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
